name: development

on:
  push:
    branches: ["master"]
    paths:
      - 'components/**'
      - 'main/**'
      - 'test/**'
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    paths:
      - 'components/**'
      - 'main/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RUN_RENAME_PROJECT_SCRIPT: ${{true}}
      ESP_DOCKER_IMAGE: gfurtadoalmeida/esp32-docker-sonar:v5.1

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # This is needed only if you are working on the
    # esp32-project-template project; remove this step
    # if you are using this project as a template.
    - name: Run Rename-Project.ps1
      if: ${{env.RUN_RENAME_PROJECT_SCRIPT}}
      shell: pwsh
      run: ./Rename-Project.ps1 '${{github.workspace}}' esp32-project-template

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Pull ESP-IDF Image
      shell: pwsh
      run: docker pull ${{env.ESP_DOCKER_IMAGE}}

    - name: Build with Sonar
      shell: pwsh
      run: docker run --rm --env SONARCLOUD_ORGANIZATION=${{secrets.SONARCLOUD_ORGANIZATION}} --env SONARCLOUD_TOKEN=${{secrets.SONARCLOUD_TOKEN}} --env LC_ALL='C.UTF-8' -v ${{github.workspace}}:/project -w /project ${{env.ESP_DOCKER_IMAGE}} idf.py build

    - name: Build Test
      shell: pwsh
      run: docker run --rm --env LC_ALL='C.UTF-8' -v ${{github.workspace}}:/project -w /project ${{env.ESP_DOCKER_IMAGE}} idf.py build -C ./test
