name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      run_rename_project_script: ${{true}}
      esp_docker_image: gfurtadoalmeida/esp32-docker-sonar:v5.1

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # This is needed only if you are working on the
    # esp32-project-template project; remove this step
    # if you are using this project as a template.
    - name: Run Rename-Project.ps1
      if: ${{env.run_rename_project_script}}
      shell: pwsh
      run: ./Rename-Project.ps1 '${{github.workspace}}' esp32-project-template

    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Pull ESP-IDF Image
      shell: pwsh
      run: docker pull ${{env.esp_docker_image}}

    - name: Build with Sonar
      shell: pwsh
      run: docker run --rm --env LC_ALL='C.UTF-8' -v ${{github.workspace}}:/project -w /project ${{env.esp_docker_image}} idf.py build

    - name: Build Test
      shell: pwsh
      run: docker run --rm --env LC_ALL='C.UTF-8' -v ${{github.workspace}}:/project -w /project ${{env.esp_docker_image}} idf.py -C ./test build

  release:
    runs-on: windows-2022
    needs: [build]
    permissions:
      contents: write

    env:
      ZIP_NAME: es32-project-template.${{github.ref_name}}.zip

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create Zip
      shell: pwsh
      run: |
        $compress = @{
          Path = "*"
          CompressionLevel = "Optimal"
          DestinationPath = $Env:ZIP_NAME
        }
        Compress-Archive @compress

    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "${{env.ZIP_NAME}}"
        makeLatest: true
        removeArtifacts: false
        replacesArtifacts: true
